---
title: "viz"
output: html_document
---

## Here are some of my data visualization works:

### 1. co-work website: [What makes the world happy?](https://gaotongliu.github.io/P8105_final_report.io/index.html)
As civilizations are developing, the happiness of human being becomes an ambiguous topic. Simple material enjoyment is no longer the only determinant of mental pleasure. So, how the state of happiness in the world change overtime and what makes the world happy? In this project, We are trying to find the reasons, and our final goal is to provide helpful information for governments to make better decisions with respect to higher life evaluation.

### 2. [dashboard show-case](dashboard.html)

The instavart dataset with 1384617 observations and 15 variables gives online order information for 131209 users, who only have single order respectively.

The information focus on the following dimension: 

**firstly**, detailed order information, including order composition(suggested by `product_id`, `product_name`, `aisle_id`, `department_id`, `aisle`, `department`), and order time (accurate to hour, suggested by variables `order_dow`, `order_hour_of_day`);

**secondly**, the users’ order frequency, which is illustrated by order sequence number for the specific user(suggested by `order_number`) and shopping interval(suggested by `days_since_prior_order`); 

**thirdly**, users shopping preferrence can also be analysed by the order adding to cart and reorder information(suggested by `add_to_cart_order`, `reordered`,respectively).

here is the exploratory [dashboard](dashboard.html) of instacart, focusing on the most popular online shopping aisles and the most frequent order hours in week days.

### 3. [tableau work file](https://public.tableau.com/profile/yuqi.miao#!/)
